[tool.poetry]
name = "divent"
version = "1.0.4"
description = "The discord scheduled event calendar generator"
authors = ["XÃ©fir Destiny"]
license = "WTFPL"
readme = "README.md"
homepage = "https://divent.crystalyx.net/"
repository = "https://git.crystalyx.net/Xefir/Divent"

[tool.poetry.scripts]
divent = 'divent.bot:__main__'

[tool.poetry.dependencies]
python = "^3.8"
disnake = "2.5.2"
ics = "0.8.0.dev0"
python-dotenv = "0.21.0"
quart = "0.18.0"
sentry-sdk = "1.9.8"
uvicorn = "0.18.3"

[tool.poetry.dev-dependencies]
flake8 = "5.0.4"
black = "22.8.0"
mypy = "0.971"
flake8-alphabetize = "0.0.17"
flake8-black = "0.3.3"
djlint = "1.12.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.djlint]
extension = "j2"
profile = "jinja"
