[tool.poetry]
name = "syndb-cassandra"
version = "2.0.1"
description = "Casssandra driver assembly for SynDB"
authors = ["Can H. Tartanoglu <canhtart@gmail.com>"]
license = "BSD-4-Clause"
readme = "README.md"
packages = [{include = "syndb_cassandra"}]

[tool.poetry.dependencies]
python = "^3.10"
click = "^8.1.3"

cassandra-driver = {version = "^3.21.0", optional = true}
pydantic = {version = "^1.9.0", optional = true}
orjson = {version = "*", optional = true}

syndb-admin = "*"

[tool.poetry.dev-dependencies]
black = "*"
isort = "*"

pytest = "^7.1.2"
pytest-env = "^0.6.2"
httpx = "^0.23.0"
asyncio = "^3.4.3"
pytest-asyncio = "^0.18.3"
pandas = "^1.4.3"

[tool.poetry.extras]
driver = ["cassandra-driver", "pydantic", "orjson"]

[tool.poetry.scripts]
sycass = 'syndb_cassandra.cli:syndb_cassandra_cli'

[tool.pytest.ini_options]
env = ["CQLENG_ALLOW_SCHEMA_MANAGEMENT=1"]

[tool.isort]
profile = "black"

[tool.black]
line-length = 120
target-version = ["py310"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
