[tool.poetry]
name = "datafet"
version = "0.5.4"
description = "Few libriaries that we need to use in more than one project"
authors = [
    "Istvan Szukacs <istvan@datadeft.eu>",
    "Krisztina Balogh <kriszti@datadeft.eu>"
]

[tool.poetry.dependencies]
python = "^3.9"
Jinja2 = "^3.1.2"
PyJWT = "^2.4.0"
boto3 = "^1.24.46"
boto3-stubs = "^1.24.63"
botocore = "^1.27.46"
cryptography = "^37.0.4"
ecdsa = "^0.18.0"
email-validator = "^1.2.1"
fastapi = "^0.79.0"
mangum = "^0.15.0"
mypy-boto3-athena = "^1.24.36"
mypy-boto3-s3 = "^1.24.36"
mypy-boto3-secretsmanager = "^1.24.54"
mypy-boto3-sqs = "^1.24.40"
pydantic = "^1.9.1"
python-dateutil = "^2.8.2"
pytz = "^2022.1"
spookyhash = "^2.1.0"
tomli = "^2.0.1"
types-python-dateutil = "^2.8.19"
types-pytz = "^2022.2.1"
mypy-boto3-ses = "^1.24.36"


[tool.poetry.dev-dependencies]
mypy = "^0.971"
pre-commit = "^2.20.0"
pytest = "^7.1"
requests = "^2.28.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
log_cli = true
log_cli_level = "INFO"
log_cli_format = "%(asctime)s [%(levelname)8s] %(message)s (%(filename)s:%(lineno)s)"
log_cli_date_format = "%Y-%m-%d %H:%M:%S"
