[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "sci-streak"
version = "0.2.2"
authors = [
  { name="Dallas Strandell", email="dstrande@live.ca" },
]
description = "Python GUI for initial analysis and plotting of Streak Camera data"
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: Microsoft :: Windows :: Windows 10",
]
dependencies = [
  "pyside6>=6.3",
  "numpy>=1.23",
  "h5py>=3.7",
  "scipy>=1.8",
  "matplotlib>=3.4",
  "pyqygraph>=0.12",
  "lmfit>=1.0",
]


[project.urls]
"Homepage" = "https://github.com/dstrande/sci-streak"
"Bug Tracker" = "https://github.com/dstrande/sci-streak/issues"
