[tool.poetry]
name = "dh-potluck"
version = "1.5.3"
authors = []
description = ""

[tool.poetry.dependencies]
python = "^3.8"
flask = "^2.1.2"
marshmallow = "3.17.0"
sqlalchemy = "^1.3"
ddtrace = "1.1.1"
boltons = "^20.2.1"
Werkzeug = ">=0.15.0"
requests = "^2.22"
flask-limiter = "^2.2.0"
json-log-formatter = "^0.3.0"
flask_sqlalchemy = "^2.4.4"
flask-smorest = "^0.38.1"
confluent-kafka = "^1.6.0"
mandrill = "^1.0.60"
mixpanel = "^4.9.0"
boto3 = "^1.17.102"

[tool.poetry.dev-dependencies]
flake8 = "^3.7"
pytest = "^4.4"
flake8-quotes = "^1.0"
vcrpy = "^2.0"
freezegun = "^0.3.15"
redis = "^3.4.1"
black = "^22.1.0"
isort = "^5.7.0"

[tool.black]
line-length = 100
skip-string-normalization = true
target-version = ['py36']

[tool.isort]
line_length = 100
include_trailing_comma = true
multi_line_output = 3
