[tool.poetry]
authors = ["Craig Trim <craigtrim@gmail.com>"]
description = "Tools for Automating the Construction of an Ontology (OWL)"
name = "owl-builder"
version = "0.1.8"

[tool.poetry.dependencies]
baseblock = "*"
fuzzywuzzy = "^0.18.0"
nltk = "^3.7"
openai = "^0.20.0"
pandas = "^1.4.0"
python = "3.8.5"
python-Levenshtein = "*"
rdflib = "^6.1.1"
regex = "2022.7.9"
spacy = "3.3"
tabulate = "*"
textacy = "0.12.0"
textblob = "^0.17.1"

[tool.poetry.dev-dependencies]
autopep8 = "*"
en-core-web-sm = {path = "resources/lib/en_core_web_sm-3.3.0.tar.gz"}
pytest = "*"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]
