[build-system]
requires      = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "warplol"
version = "1.1.0"
description = "Short URLs using the warp.lol APIs."
readme = "README.md"
authors = [{ name = "Filippo Romani", email = "mail@filipporomani.it" }]
license = { file = "LICENSE" }
classifiers=[
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.7",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Topic :: Software Development :: Libraries :: Python Modules",
        "Development Status :: 4 - Beta",
        "Operating System :: OS Independent"
]
keywords = ["api", "warplol", "url", "shortener", "short", "shorturl", "short-url"]
dependencies = [
    "requests"
]
requires-python = ">=3.6"

[project.urls]
Homepage = "https://warp.lol"
